"""NitePR5 session core — connect, target, maps, peephole R/W, turbo scan, watch, freeze, cheats.

Put ``web/`` on ``sys.path``::

    from nitepr5_core import Session, MockTransport, discover, resolve_host
"""

from __future__ import annotations

from .constants import (
    CONNECT_TIMEOUT,
    FREEZE_MAX,
    HEX_PEEPHOLE_DEFAULT,
    PS5DEBUG_PORT,
    READ_MAX,
    RESULTS_MAX,
    SCAN_ALIGN_U32,
    SCAN_IO_TIMEOUT,
    SCAN_REGIONS_DEFAULT,
    WATCH_MAX,
    WATCH_SIZE_DEFAULT,
    WATCH_SIZES,
    WRITE_MAX,
)
from .errors import (
    ConnectFailed,
    FreezeLimit,
    InvalidCheat,
    InvalidFreezeSize,
    InvalidReadSize,
    InvalidResultLimit,
    InvalidScanCompare,
    InvalidScanRegions,
    InvalidScanValue,
    InvalidWatchSize,
    InvalidWriteSize,
    NitePR5Error,
    NoCheat,
    NoFreeze,
    NoMod,
    NoScan,
    NoTarget,
    NoWatch,
    NotConnected,
    ReadTooLarge,
    ResultsTooMany,
    ScanActive,
    ScanInFlight,
    ScanUnsupported,
    UndoTooLarge,
    WatchLimit,
    WriteTooLarge,
)
from .host import discover, resolve_host
from .session import Session
from .transport import MockTransport, Ps5dbgTransport
from .types import (
    CheatFile,
    CheatMod,
    CheatPatch,
    FreezeEntry,
    ForegroundInfo,
    MemoryMap,
    ProcessInfo,
    ScanHit,
    WatchEntry,
    WatchValue,
)

__all__ = [
    "CONNECT_TIMEOUT",
    "FREEZE_MAX",
    "HEX_PEEPHOLE_DEFAULT",
    "PS5DEBUG_PORT",
    "READ_MAX",
    "RESULTS_MAX",
    "SCAN_ALIGN_U32",
    "SCAN_IO_TIMEOUT",
    "SCAN_REGIONS_DEFAULT",
    "WATCH_MAX",
    "WATCH_SIZE_DEFAULT",
    "WATCH_SIZES",
    "WRITE_MAX",
    "CheatFile",
    "CheatMod",
    "CheatPatch",
    "ConnectFailed",
    "FreezeEntry",
    "FreezeLimit",
    "InvalidCheat",
    "InvalidFreezeSize",
    "InvalidReadSize",
    "InvalidResultLimit",
    "InvalidScanCompare",
    "InvalidScanRegions",
    "InvalidScanValue",
    "InvalidWatchSize",
    "InvalidWriteSize",
    "NitePR5Error",
    "NoCheat",
    "NoFreeze",
    "NoMod",
    "NoScan",
    "NoTarget",
    "NoWatch",
    "NotConnected",
    "ReadTooLarge",
    "ResultsTooMany",
    "ScanActive",
    "ScanHit",
    "ScanInFlight",
    "ScanUnsupported",
    "UndoTooLarge",
    "WatchEntry",
    "WatchLimit",
    "WatchValue",
    "WriteTooLarge",
    "discover",
    "resolve_host",
    "Session",
    "MockTransport",
    "Ps5dbgTransport",
    "ForegroundInfo",
    "MemoryMap",
    "ProcessInfo",
]
